@startuml

!theme monokai from ..\data

hide enum empty members
hide class empty members


enum GameMode {
    PVP
    PVB
    BVB
}
enum DifficultyLvl {
    EASY
    HARD
}


abstract class Player {
    +card: Card
    +fail: <i>bool</i>
    +action() → <i>bool</i>
    -next() → <i>bool</i>
    -strike() → <i>bool</i>
}


class Human {
    +action() → <i>bool</i>
}


class Bot {
    +difficulty: DifficultyLvl
    +action() → <i>bool</i>
}


class Game {
    +mode: GameMode
    +players: <i>list</i>[Player]
    +purse: <i>set</i>[Token]
    +start() → Player
    -check_fail() → <i>bool</i>
}


frame " main  " {
    class Controller {
        {method}...
        +get_input() → Answer
        {method}...
    }
}


Player <|-- Human
Player <|-- Bot

Human ...> Controller::get_input

Bot o-- DifficultyLvl

Game o-left- GameMode
Game o-down- Player

Game ..> Player


DifficultyLvl -[hidden]- Controller
Human -right[hidden]- Bot


@enduml