@startuml

!theme monokai from ..\data

hide abstract empty members


abstract class int
abstract class tuple
abstract class list


class Token {
    +{static}minimum: <i>int</i> = 1
    +{static}maximum: <i>int</i> = 90
    +strike: <i>bool</i> = False
    __new__()
    __init__()
    __str__()
}


class Row {
    +{static}cells: <i>int</i> = 9
    +{static}tokens: <i>int</i> = 5
    __new__()
    __str__()
}


class Card {
    +{static}rows: <i>int</i> = 3
    __init__()
    __str__()
}


int <|--- Token
tuple <|-- Row
list <|-- Card

Row o-- Token
Card *-right- Row
Card o-- Token


@enduml